name: dev-daily-release

on:
  push:
    branches:
      - dev

jobs:
  create_dev_release:
    name: Create dev release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Generate release name
        id: get_release_name
        run: |
          # 日付ベースのリリース名を生成（dev-YYYYMMDD形式）
          DATE=$(date +'%Y%m%d')
          echo "RELEASE_NAME=dev-${DATE}" >> $GITHUB_OUTPUT
          echo "RELEASE_DESCRIPTION=Development build for $(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.get_release_name.outputs.RELEASE_NAME }}
          release_name: ${{ steps.get_release_name.outputs.RELEASE_NAME }}
          body: ${{ steps.get_release_name.outputs.RELEASE_DESCRIPTION }}
          draft: false
          prerelease: false

  build_linux:
    name: "Build Linux packages"
    runs-on: ubuntu-latest
    needs: create_dev_release
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build packages
        run: |
          docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 --output 'type=local,dest=dist'
      - name: Upload x86_64 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_dev_release.outputs.upload_url }}
          asset_path: dist/linux_amd64/piper_amd64.tar.gz
          asset_name: piper_linux_x86_64.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload ARM64 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_dev_release.outputs.upload_url }}
          asset_path: dist/linux_arm64/piper_arm64.tar.gz
          asset_name: piper_linux_aarch64.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload ARMv7 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_dev_release.outputs.upload_url }}
          asset_path: dist/linux_arm_v7/piper_armv7.tar.gz
          asset_name: piper_linux_armv7l.tar.gz
          asset_content_type: application/octet-stream

  build_windows:
    name: "Build Windows package"
    runs-on: windows-latest
    needs: create_dev_release
    steps:
      - uses: actions/checkout@v3
      - name: Configure build
        run: |
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=_install/piper
      - name: Build package
        run: |
          cmake --build build --config Release
      - name: Install package
        run: |
          cmake --install build
      - name: Create archive
        run: |
          cd _install
          Compress-Archive -LiteralPath piper -DestinationPath piper_windows_amd64.zip
      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_dev_release.outputs.upload_url }}
          asset_path: _install/piper_windows_amd64.zip
          asset_name: piper_windows_amd64.zip
          asset_content_type: application/zip

  build_macos:
    name: "Build macOS packages"
    runs-on: macos-latest
    needs: create_dev_release
    strategy:
      fail-fast: true
      matrix:
        arch: [x64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Configure build
        run: |
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=_install/piper
      - name: Build package
        run: |
          cmake --build build --config Release
      - name: Install package
        run: |
          cmake --install build
      - name: Create archive
        run: |
          cd _install && \
          tar -czf piper_macos_${{ matrix.arch }}.tar.gz piper/
      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_dev_release.outputs.upload_url }}
          asset_path: _install/piper_macos_${{ matrix.arch }}.tar.gz
          asset_name: piper_macos_${{ matrix.arch }}.tar.gz
          asset_content_type: application/octet-stream
